apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: autoExport
  namespace: monitoring
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: autoExport
    spec:
      containers:
        - name: autoExport
          image: autoexport:v0.0.1
          ports:
            - containerPort: 8000
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 600
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: autoExport
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: webhook
    port: 8000
    targetPort: 8000
  selector:
    app: autoExport
  sessionAffinity: ClientIP
