apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
     app: autoexport
  name: autoexport
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: autoexport
  endpoints:
  - port: autometrics
    scheme: http
    interval: 30s
    path: '/api/autoMetric/Apimetric'
  - port: autometrics
    scheme: http
    interval: 30s
    path: '/api/autoMetric/urlRequest'
  - port: autometrics
    scheme: http
    interval: 30s
    path: '/api/autoMetric/faceStatus'
