apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
     app: autoexport
  name: autoexport
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: monitoring
  endpoints:
  - port: metrics
    scheme: http
    interval: 30s
    path: '/api/autoMetric/Apimetric'
    honorLabels: true
