apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
     app: autoexport
  name: autoexport
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: autoexport
  endpoints:
  - port: metrics
    scheme: http
    path: '/api/autoMetric/Apimetric'